version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install 'poetry==1.6.1'
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      - poetry install -C "forcedimension_core-python" --with docs --extras numpy

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

submodules:
  include: all
